### ISSUE TITLE
AttributeError: Calling operator "bpy.ops.wm.console_toggle" error, could not be found

### ISSUE THREAD

**Issue by NahidSafari** [MoritzB90/PyRID#2]
Hi, 

While following the instruction to run  ".prop and .xyz" files on blender to visualize Hard_Sphere_Fluid, I faced the following error (on blender):

 **AttributeError: Calling operator "bpy.ops.wm.console_toggle" error, could not be found**

It seems this issue arises because I am executing codes on Unix. Unfortunately, I do not know how I can resolve it. 

Best,
Nahid

**Comment by MoritzB90** [comment]
Hi Nahid,

thanks for reporting this! I have updated the Blender addon, which now also works on Linux. The problem was that the addon automatically started the blender console, which is not available on Linux. Therefore, I recommend you always start Blender via the console on Linux when you want to use the PyRID addon because rendering progress and such are output to the console if you use the render button from the addon.

Best,
Moritz
